apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.18.2
    helm:
      releaseName: crossplane
      valuesObject:
        createNamespace: true
        replicas: 2
        serviceAccount:
          customAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::933066587362:role/argo-cd-control-plane-lorenzo-control-plane
  destination:
    name: replaceme
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false