apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
    name: crossplane
  path: target-cluster.yaml
- target:
    kind: Application
    name: crossplane
  path: name.yaml
- target:
    kind: Application
    name: crossplane
  path: version.yaml