apiVersion: kubernetes.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: monitoring-kubeconfig
      key: kubeconfig