apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: data-plane
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: data-plane-kubeconfig
      key: kubeconfig