apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xelasticstacks.eck.crossplane.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  group: eck.crossplane.io
  names:
    kind: XElasticStack
    plural: xelasticstacks
  claimNames:
    kind: ElasticStack
    plural: elasticstacks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                aws:
                  type: object
                  properties:
                    account_id:
                      type: string
                    partition:
                      type: string
                    region: 
                      type: string
                version:
                  type: string
                elasticsearch:
                  type: object
                  properties:
                    nodeCount:
                      type: integer
                kibana:
                  type: object
                  properties:
                    nodeCount:
                      type: integer
                targetCluster:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
              required:
                - aws
                - version
                - elasticsearch
                - kibana
                - targetCluster